In [1]:
import pandas as pd

df=pd.read_csv("Crop_recommendation.csv")

In [3]:
df.label.value_counts()

rice           100
maize          100
jute           100
cotton         100
coconut        100
papaya         100
orange         100
apple          100
muskmelon      100
watermelon     100
grapes         100
mango          100
banana         100
pomegranate    100
lentil         100
blackgram      100
mungbean       100
mothbeans      100
pigeonpeas     100
kidneybeans    100
chickpea       100
coffee         100
Name: label, dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB

In [22]:
import pandas as pd

crops_soil_types = {
    "Rice": "alluvial soils, black soils, deltaic soils",
    "Maize": "black soils, laterite soils, red soils",
    "Jute": "alluvial soils, deltaic soils",
    "Cotton": "black soils, red soils, laterite soils",
    "Coconut": "coastal sands, alluvial soils, black soils",
    "Papaya": "alluvial soils, black soils, red soils",
    "Orange": "laterite soils, red soils, black soils",
    "Apple": "mountain soils, forest soils",
    "Muskmelon": "alluvial soils, black soils",
    "Watermelon": "alluvial soils, black soils",
    "Grapes": "alluvial soils, black soils, red soils",
    "Mango": "laterite soils, red soils, black soils",
    "Banana": "alluvial soils, deltaic soils, coastal sands",
    "Pomegranate": "laterite soils, red soils, black soils",
    "Lentil": "black soils, alluvial soils",
    "Blackgram": "black soils, alluvial soils",
    "Mungbean": "black soils, alluvial soils",
    "Mothbeans": "black soils, alluvial soils",
    "Pigeonpeas": "black soils, alluvial soils",
    "Kidneybeans": "black soils, alluvial soils",
    "Chickpea": "black soils, alluvial soils",
    "Coffee": "mountain soils, forest soils"
}

# Get a list of all unique soil types
unique_soil_types = set()
for soil_types in crops_soil_types.values():
    soil_types = soil_types.split(", ")
    unique_soil_types |= set(soil_types)
unique_soil_types = list(unique_soil_types)

# Initialize a dataframe with one-hot encoded columns for each soil type
df1 = pd.DataFrame(columns=unique_soil_types)

# Populate the dataframe with one-hot encoded values for each crop
for crop, soil_types in crops_soil_types.items():
    soil_types = soil_types.split(", ")
    values = [1 if soil_type in soil_types else 0 for soil_type in unique_soil_types]
    df1 = df1.append(pd.Series(values, index=df1.columns, name=crop))

# Reset the index of the dataframe
df1 = df1.reset_index()
df1 = df1.rename(columns={"index": "Crop"})

print(df1)

C:\Users\Aakash\AppData\Local\Temp\ipykernel_8136\4108490488.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(pd.Series(values, index=df1.columns, name=crop))
C:\Users\Aakash\AppData\Local\Temp\ipykernel_8136\4108490488.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(pd.Series(values, index=df1.columns, name=crop))
C:\Users\Aakash\AppData\Local\Temp\ipykernel_8136\4108490488.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(pd.Series(values, index=df1.columns, name=crop))
C:\Users\Aakash\AppData\Local\Temp\ipykernel_8136\4108490488.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(pd.Series(values, index=df1.columns, name=crop))
C:\Users\Aakash\AppData\Local\Temp\ipykernel_8136\4108490488.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(pd.Series(values, index=df1.columns, name=crop))
C:\Users\Aakash\AppData\Local\Temp\ipykernel_8136\4108490488.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(pd.Series(values, index=df1.columns, name=crop))
C:\Users\Aakash\AppData\Local\Temp\ipykernel_8136\4108490488.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(pd.Series(values, index=df1.columns, name=crop))
C:\Users\Aakash\AppData\Local\Temp\ipykernel_8136\4108490488.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(pd.Series(values, index=df1.columns, name=crop))
C:\Users\Aakash\AppData\Local\Temp\ipykernel_8136\4108490488.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(pd.Series(values, index=df1.columns, name=crop))
C:\Users\Aakash\AppData\Local\Temp\ipykernel_8136\4108490488.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(pd.Series(values, index=df1.columns, name=crop))
C:\Users\Aakash\AppData\Local\Temp\ipykernel_8136\4108490488.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(pd.Series(values, index=df1.columns, name=crop))

           Crop forest soils mountain soils black soils laterite soils  \
0          Rice            0              0           1              0
1         Maize            0              0           1              1
2          Jute            0              0           0              0
3        Cotton            0              0           1              1
4       Coconut            0              0           1              0
5        Papaya            0              0           1              0
6        Orange            0              0           1              1
7         Apple            1              1           0              0
8     Muskmelon            0              0           1              0
9    Watermelon            0              0           1              0
10       Grapes            0              0           1              0
11        Mango            0              0           1              1
12       Banana            0              0           0              0
13  Pomegranate            0              0           1              1
14       Lentil            0              0           1              0
15    Blackgram            0              0           1              0
16     Mungbean            0              0           1              0
17    Mothbeans            0              0           1              0
18   Pigeonpeas            0              0           1              0
19  Kidneybeans            0              0           1              0
20     Chickpea            0              0           1              0
21       Coffee            1              1           0              0

   alluvial soils red soils deltaic soils coastal sands
0               1         0             1             0
1               0         1             0             0
2               1         0             1             0
3               0         1             0             0
4               1         0             0             1
5               1         1             0             0
6               0         1             0             0
7               0         0             0             0
8               1         0             0             0
9               1         0             0             0
10              1         1             0             0
11              0         1             0             0
12              1         0             1             1
13              0         1             0             0
14              1         0             0             0
15              1         0             0             0
16              1         0             0             0
17              1         0             0             0
18              1         0             0             0
19              1         0             0             0
20              1         0             0             0
21              0         0             0             0

C:\Users\Aakash\AppData\Local\Temp\ipykernel_8136\4108490488.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(pd.Series(values, index=df1.columns, name=crop))
C:\Users\Aakash\AppData\Local\Temp\ipykernel_8136\4108490488.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(pd.Series(values, index=df1.columns, name=crop))
C:\Users\Aakash\AppData\Local\Temp\ipykernel_8136\4108490488.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(pd.Series(values, index=df1.columns, name=crop))
C:\Users\Aakash\AppData\Local\Temp\ipykernel_8136\4108490488.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(pd.Series(values, index=df1.columns, name=crop))
C:\Users\Aakash\AppData\Local\Temp\ipykernel_8136\4108490488.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(pd.Series(values, index=df1.columns, name=crop))
C:\Users\Aakash\AppData\Local\Temp\ipykernel_8136\4108490488.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(pd.Series(values, index=df1.columns, name=crop))
C:\Users\Aakash\AppData\Local\Temp\ipykernel_8136\4108490488.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(pd.Series(values, index=df1.columns, name=crop))
C:\Users\Aakash\AppData\Local\Temp\ipykernel_8136\4108490488.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(pd.Series(values, index=df1.columns, name=crop))
C:\Users\Aakash\AppData\Local\Temp\ipykernel_8136\4108490488.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(pd.Series(values, index=df1.columns, name=crop))
C:\Users\Aakash\AppData\Local\Temp\ipykernel_8136\4108490488.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(pd.Series(values, index=df1.columns, name=crop))
C:\Users\Aakash\AppData\Local\Temp\ipykernel_8136\4108490488.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(pd.Series(values, index=df1.columns, name=crop))

In [9]:
df1

,Crop,forest soils,mountain soils,black soils,laterite soils,alluvial soils,red soils,deltaic soils,coastal sands
0,Rice,0,0,1,0,1,0,1,0
1,Maize,0,0,1,1,0,1,0,0
2,Jute,0,0,0,0,1,0,1,0
3,Cotton,0,0,1,1,0,1,0,0
4,Coconut,0,0,1,0,1,0,0,1
5,Papaya,0,0,1,0,1,1,0,0
6,Orange,0,0,1,1,0,1,0,0
7,Apple,1,1,0,0,0,0,0,0
8,Muskmelon,0,0,1,0,1,0,0,0
9,Watermelon,0,0,1,0,1,0,0,0
10,Grapes,0,0,1,0,1,1,0,0
11,Mango,0,0,1,1,0,1,0,0
12,Banana,0,0,0,0,1,0,1,1
13,Pomegranate,0,0,1,1,0,1,0,0
14,Lentil,0,0,1,0,1,0,0,0
15,Blackgram,0,0,1,0,1,0,0,0
16,Mungbean,0,0,1,0,1,0,0,0
17,Mothbeans,0,0,1,0,1,0,0,0
18,Pigeonpeas,0,0,1,0,1,0,0,0
19,Kidneybeans,0,0,1,0,1,0,0,0
20,Chickpea,0,0,1,0,1,0,0,0
21,Coffee,1,1,0,0,0,0,0,0

In [25]:
df1.Crop = df1.Crop.str.lower()

In [26]:
df1

,Crop,forest soils,mountain soils,black soils,laterite soils,alluvial soils,red soils,deltaic soils,coastal sands
0,rice,0,0,1,0,1,0,1,0
1,maize,0,0,1,1,0,1,0,0
2,jute,0,0,0,0,1,0,1,0
3,cotton,0,0,1,1,0,1,0,0
4,coconut,0,0,1,0,1,0,0,1
5,papaya,0,0,1,0,1,1,0,0
6,orange,0,0,1,1,0,1,0,0
7,apple,1,1,0,0,0,0,0,0
8,muskmelon,0,0,1,0,1,0,0,0
9,watermelon,0,0,1,0,1,0,0,0
10,grapes,0,0,1,0,1,1,0,0
11,mango,0,0,1,1,0,1,0,0
12,banana,0,0,0,0,1,0,1,1
13,pomegranate,0,0,1,1,0,1,0,0
14,lentil,0,0,1,0,1,0,0,0
15,blackgram,0,0,1,0,1,0,0,0
16,mungbean,0,0,1,0,1,0,0,0
17,mothbeans,0,0,1,0,1,0,0,0
18,pigeonpeas,0,0,1,0,1,0,0,0
19,kidneybeans,0,0,1,0,1,0,0,0
20,chickpea,0,0,1,0,1,0,0,0
21,coffee,1,1,0,0,0,0,0,0

In [42]:
df2 = df.merge(df1, how='inner',left_on="label",right_on="Crop")

In [43]:
df2 = df2.drop("Crop",axis=1)

In [44]:
extra_col = df2["N"]+df2["P"]+df2["K"]

In [45]:
df2["N"]=df2["N"]/extra_col
df2["P"]=df2["P"]/extra_col
df2["K"]=df2["K"]/extra_col

In [46]:
df2

,N,P,K,temperature,humidity,ph,rainfall,label,forest soils,mountain soils,black soils,laterite soils,alluvial soils,red soils,deltaic soils,coastal sands
0,0.514286,0.240000,0.245714,20.879744,82.002744,6.502985,202.935536,rice,0,0,1,0,1,0,1,0
1,0.461957,0.315217,0.222826,21.770462,80.319644,7.038096,226.655537,rice,0,0,1,0,1,0,1,0
2,0.377358,0.345912,0.276730,23.004459,82.320763,7.840207,263.964248,rice,0,0,1,0,1,0,1,0
3,0.496644,0.234899,0.268456,26.491096,80.158363,6.980401,242.864034,rice,0,0,1,0,1,0,1,0
4,0.481481,0.259259,0.259259,20.130175,81.604873,7.628473,262.717340,rice,0,0,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2195,0.618497,0.196532,0.184971,26.774637,66.413269,6.780064,177.774507,coffee,1,1,0,0,0,0,0,0
2196,0.702128,0.106383,0.191489,27.417112,56.636362,6.086922,127.924610,coffee,1,1,0,0,0,0,0,0
2197,0.651934,0.182320,0.165746,24.131797,67.225123,6.362608,173.322839,coffee,1,1,0,0,0,0,0,0
2198,0.639344,0.174863,0.185792,26.272418,52.127394,6.758793,127.175293,coffee,1,1,0,0,0,0,0,0
2199,0.684211,0.118421,0.197368,23.603016,60.396475,6.779833,140.937041,coffee,1,1,0,0,0,0,0,0

In [48]:
soil_ph = {
    "alluvial soils": 7.25,
    "red soils": 6.0,
    "laterite soils": 5.25,
    "black soils": 7.5,
    "coastal sands": 7.25,
    "forest soils": 6.25,
    "mountain soils": 6.25,
    "deltaic soil": 6.75
}

In [49]:
soil_npk = {
    "alluvial soils": [1.5, 0.5, 2.0],
    "red soils": [1.0, 0.5, 1.5],
    "laterite soils": [0.5, 0.25, 1.0],
    "black soils": [2.0, 0.5, 3.0],
    "coastal sands": [1.0, 0.25, 1.5],
    "forest soils": [1.5, 0.5, 2.0],
    "mountain soils": [1.0, 0.5, 1.5],
    "deltaic soil": [1.25, 0.375, 1.75]
}

In [50]:
state_soil_map = {
"andhra pradesh": ["red soils", "black soils", "laterite soils", "alluvial soils"],
"arunachal pradesh": ["forest soils", "mountain soils"],
"assam": ["alluvial soils", "laterite soils"],
"bihar": ["alluvial soils", "laterite soils"],
"chhattisgarh": ["red soils", "laterite soils", "black soils"],
"goa": ["laterite soils", "red soils"],
"haryana": ["alluvial soils", "black soils", "loamy soil"],
"himachal pradesh": ["mountain soils", "forest soils"],
"jharkhand": ["laterite soils", "red soils", "alluvial soils"],
"madhya pradesh": ["red soils", "laterite soils", "black soils", "alluvial soils"],
"maharashtra": ["black soils", "red soils", "laterite soils", "alluvial soils"],
"manipur": ["forest soils", "mountain soils"],
"meghalaya": ["forest soils", "mountain soils"],
"mizoram": ["mountain soils", "forest soils"],
"nagaland": ["forest soils", "mountain soils"],
"odisha": ["laterite soils", "red soils", "alluvial soils"],
"punjab": ["black soils", "alluvial soils", "loamy soil"],
"sikkim": ["mountain soils", "forest soils"],
"tamil nadu": ["red soils", "laterite soils", "alluvial soils"],
"telangana": ["red soils", "black soils", "laterite soils"],
"tripura": ["laterite soils", "alluvial soils"],
"uttar pradesh": ["alluvial soils", "laterite soils"],
"uttarakhand": ["mountain soils", "forest soils"],
"west bengal": ["alluvial soils", "laterite soils"],
"andaman and nicobar islands": ["laterite soils", "forest soils"],
"chandigarh": ["alluvial soils"],
"dadra and nagar haveli": ["laterite soils"],
"daman and diu": ["laterite soils"],
"delhi": ["alluvial soils"],
"lakshadweep": ["coral soils"],
"puducherry": ["laterite soils", "alluvial soils"]
}

In [52]:
rajasthan_soil_map = {
"Ajmer": ["laterite soils", "red soils", "alluvial soils"],
"Alwar": ["red soils", "alluvial soils", "laterite soils"],
"Banswara": ["red soils", "laterite soils"],
"Baran": ["red soils", "alluvial soils"],
"Barmer": ["red soils", "laterite soils"],
"Bharatpur": ["alluvial soils", "red soils"],
"Bhilwara": ["red soils", "alluvial soils"],
"Bikaner": ["red soils", "laterite soils"],
"Bundi": ["red soils", "laterite soils"],
"Chittorgarh": ["red soils", "laterite soils"],
"Churu": ["red soils", "laterite soils"],
"Dausa": ["red soils", "laterite soils"],
"Dholpur": ["alluvial soils", "red soils"],
"Dungarpur": ["red soils", "laterite soils"],
"Hanumangarh": ["red soils", "laterite soils"],
"Jaipur": ["red soils", "alluvial soils", "laterite soils"],
"Jaisalmer": ["red soils", "laterite soils"],
"Jalor": ["red soils", "laterite soils"],
"Jhalawar": ["red soils", "laterite soils"],
"Jhunjhunu": ["red soils", "laterite soils"],
"Jodhpur": ["red soils", "laterite soils"],
"Karauli": ["alluvial soils", "red soils"],
"Kota": ["red soils", "laterite soils"],
"Nagaur": ["red soils", "laterite soils"],
"Pali": ["red soils", "laterite soils"],
"Rajsamand": ["red soils", "alluvial soils", "laterite soils"],
"Sawai Madhopur": ["red soils", "laterite soils"],
"Sikar": ["red soils", "laterite soils"],
"Sirohi": ["red soils", "laterite soils"],
"Tonk": ["red soils", "laterite soils"],
"Udaipur": ["red soils", "laterite soils"]
}

In [56]:
gujarat_soil_map = {
 'Ahmedabad': ['black soils', 'laterite soils'],
 'Amreli': ['black soils', 'laterite soils'],
 'Anand': ['black soils', 'alluvial soils'],
 'Banaskantha': ['black soils', 'alluvial soils'],
 'Bharuch': ['alluvial soils', 'black soils'],
 'Bhavnagar': ['black soils', 'laterite soils'],
 'Dahod': ['black soils', 'alluvial soils'],
 'Dang': ['black soils', 'laterite soils'],
 'Gandhinagar': ['black soils', 'alluvial soils'],
 'Jamnagar': ['black soils', 'laterite soils'],
 'Junagadh': ['black soils', 'laterite soils'],
 'Kachchh': ['black soils', 'laterite soils'],
 'Kheda': ['black soils', 'alluvial soils'],
 'Mehsana': ['black soils', 'alluvial soils'],
 'Narmada': ['black soils', 'alluvial soils'],
 'Navsari': ['black soils', 'alluvial soils'],
 'Panchmahal': ['black soils', 'alluvial soils'],
 'Patan': ['black soils', 'alluvial soils'],
 'Porbandar': ['black soils', 'laterite soils'],
 'Rajkot': ['black soils', 'laterite soils'],
 'Sabarkantha': ['black soils', 'alluvial soils'],
 'Surat': ['black soils', 'alluvial soils'],
 'Surendranagar': ['black soils', 'laterite soils'],
 'Tapi': ['black soils', 'alluvial soils'],
 'Vadodara': ['black soils', 'alluvial soils'],
 'Valsad': ['black soils', 'alluvial soils']
}

In [57]:
kerala_soil_map={
 'Thiruvananthapuram': ['laterite soils', 'red soils'],
 'Kollam': ['laterite soils', 'red soils', 'alluvial soils'],
 'Pathanamthitta': ['laterite soils', 'red soils', 'forest soils'],
 'Alappuzha': ['laterite soils', 'red soils', 'alluvial soils'],
 'Kottayam': ['laterite soils', 'red soils', 'alluvial soils'],
 'Idukki': ['laterite soils', 'red soils', 'forest soils'],
 'Ernakulam': ['laterite soils', 'red soils', 'alluvial soils'],
 'Thrissur': ['laterite soils', 'red soils', 'alluvial soils'],
 'Palakkad': ['laterite soils', 'red soils', 'alluvial soils'],
 'Malappuram': ['laterite soils', 'red soils', 'alluvial soils'],
 'Kozhikode': ['laterite soils', 'red soils', 'alluvial soils'],
 'Wayanad': ['laterite soils', 'red soils', 'forest soils'],
 'Kannur': ['laterite soils', 'red soils', 'alluvial soils'],
 'Kasaragod': ['laterite soils', 'red soils']
}

In [59]:
karnataka_soil_map = {
 ' Bengaluru': ['red soils', 'black soils'],
 'Belagavi': ['red soils', 'black soils', 'laterite soils'],
 'Ballari': ['red soils', 'laterite soils'],
 'Bidar': ['red soils', 'black soils'],
 'Vijayapura': ['red soils', 'laterite soils'],
 'Chikkamagaluru': ['red soils', 'laterite soils', 'forest soils'],
 'Chitradurga': ['red soils', 'laterite soils'],
 'Davangere': ['red soils', 'black soils'],
 'Dharwad': ['red soils', 'laterite soils'],
 'Gadag': ['red soils', 'laterite soils'],
 'Kalaburagi': ['red soils', 'black soils'],
 'Hassan': ['red soils', 'laterite soils'],
 'Haveri': ['red soils', 'black soils'],
 'Kolar': ['red soils', 'black soils'],
 'Koppal': ['red soils', 'laterite soils'],
 'Mandya': ['red soils', 'black soils'],
 'Mysuru': ['red soils', 'black soils'],
 'Raichur': ['red soils', 'black soils'],
 'Ramanagara': ['red soils', 'black soils'],
 'Shivamogga': ['red soils', 'laterite soils'],
 'Tumakuru': ['red soils', 'black soils'],
 'Udupi': ['laterite soils', 'red soils'],
 'Uttara Kannada': ['laterite soils', 'red soils', 'forest soils'],
 'Yadgir': ['red soils']
}

In [72]:
train_cols = [x for x in df2.columns if x!='label']
train_cols1=["N","P","K","temperature","humidity","ph","rainfall"]

In [65]:
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import accuracy_score

In [113]:
le = preprocessing.LabelEncoder()
X = df2.loc[:, train_cols]
y = df['label']
y = le.fit_transform(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
X

,N,P,K,temperature,humidity,ph,rainfall,forest soils,mountain soils,black soils,laterite soils,alluvial soils,red soils,deltaic soils,coastal sands
0,0.514286,0.240000,0.245714,20.879744,82.002744,6.502985,202.935536,0,0,1,0,1,0,1,0
1,0.461957,0.315217,0.222826,21.770462,80.319644,7.038096,226.655537,0,0,1,0,1,0,1,0
2,0.377358,0.345912,0.276730,23.004459,82.320763,7.840207,263.964248,0,0,1,0,1,0,1,0
3,0.496644,0.234899,0.268456,26.491096,80.158363,6.980401,242.864034,0,0,1,0,1,0,1,0
4,0.481481,0.259259,0.259259,20.130175,81.604873,7.628473,262.717340,0,0,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2195,0.618497,0.196532,0.184971,26.774637,66.413269,6.780064,177.774507,1,1,0,0,0,0,0,0
2196,0.702128,0.106383,0.191489,27.417112,56.636362,6.086922,127.924610,1,1,0,0,0,0,0,0
2197,0.651934,0.182320,0.165746,24.131797,67.225123,6.362608,173.322839,1,1,0,0,0,0,0,0
2198,0.639344,0.174863,0.185792,26.272418,52.127394,6.758793,127.175293,1,1,0,0,0,0,0,0
2199,0.684211,0.118421,0.197368,23.603016,60.396475,6.779833,140.937041,1,1,0,0,0,0,0,0

In [131]:
from sklearn.ensemble import RandomForestClassifier

forest = RandomForestClassifier(criterion='gini',n_estimators=3,random_state=0,n_jobs=3)

forest.fit(X_train, y_train)

y_pred = forest.predict(X_test)
print('Accuracy: %.3f' % accuracy_score(y_test, y_pred))

Accuracy: 0.984

In [130]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(max_depth=12)
y_pred = clf.fit(X_train, y_train).predict(X_test)
accuracy_score(y_test, y_pred)

0.9772727272727273